export const keywords = [
  "registro de marcas",
  "marca registrada",
  "registro de marca no Brasil",
  "como registrar uma marca",
  "registro de marca INPI",
  "proteção de marca",
  "marca e patente",
  "propriedade intelectual",
  "processo de registro de marca",
  "marca comercial",
  "consulta de marca registrada",
  "pesquisa de marcas",
  "registro de logomarca",
  "direitos sobre marcas",

  // Legal and Regulatory
  "registro de marca INPI (Instituto Nacional da Propriedade Industrial)",
  "legislação de marcas",
  "lei de marcas e patentes",
  "proteção legal de marca",
  "custos de registro de marca",
  "requerimento de marca",
  "regularização de marca",
  "processo legal de registro de marca",
  "renovação de marca registrada",
  "registro de marca internacional",
  "oposição de marca",
  "monitoramento de marca registrada",

  // Industry-Specific Keywords
  "registro de marca para empresa",
  "registro de marca para produtos",
  "registro de marca para serviços",
  "registro de nome fantasia",
  "registro de marca para startups",
  "registro de marca para e-commerce",
  "marca registrada para franquias",
  "registro de marca no setor de moda",
  "registro de marca para software",
  "registro de marca para alimentos e bebidas",

  // Business-Oriented Keywords
  "vantagens do registro de marca",
  "importância do registro de marca",
  "proteção de nome de empresa",
  "valor de uma marca registrada",
  "como proteger sua marca",
  "consulta de disponibilidade de marca",
  "registro de marca empresarial",
  "segurança jurídica para marcas",
  "registro de marcas em tribunais",

  // Procedural Keywords
  "como dar entrada no registro de marca",
  "etapas do registro de marca",
  "como acompanhar o registro de marca",
  "quanto tempo demora para registrar uma marca",
  "documentação para registro de marca",
  "guia completo para registrar uma marca",
  "etapas de proteção de marca",

  // Competitor and Defense Keywords
  "defesa de marca registrada",
  "violação de marca registrada",
  "ação judicial por marca registrada",
  "evitar plágio de marca",
  "disputa de marca registrada",
  "conflito de marcas",
];
